### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by raisilhamn** [dwisiswant0/WiFiID#1]
mas dwi ini punya saya kok cuma detek 3 mac mulu ya. 
padahal tempatnya rame orang tapi ngga detek macnya 
tq mas dwi

**Comment by dwisiswant0** [comment]
Terima kasih masukannya. Di TKP saya juga sama. Mangkannya ini diflag
sebagai beta, tunggu update-an selanjutnya ya.

Pada tanggal Sen, 26 Mar 2018 10.17 PM, raisilhamn <notifications@github.com>
menulis:
